# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    mkdir ~/tmp
    cd ~/tmp
    wget 'https://github.com/gohugoio/hugo/releases/download/v0.66.0/hugo_0.66.0_Linux-64bit.tar.gz'
    tar zxvf hugo_0.66.0_Linux-64bit.tar.gz
    mv hugo $(GOBIN)
  displayName: 'Set up Hugo'

- script: |
    hugo version
  displayName: 'Check Hugo version'

- script: |
    npm install
  displayName: 'Setup npm module'

- script: |
    npx ts-node src/app.ts &
  displayName: 'Run json api server'

- script: |
    hugo --gc
  displayName: 'Build content by hugo'

- script: |
    git clone https://meganii:$(GITHUB_PARSONAL_ACCESS_TOKEN)@github.com/meganii/www.meganii.com
    cp -rp public/* www.meganii.com
    cd www.meganii.com
    git config --local user.name $(GIT_USER)
    git config --local user.email $(GIT_EMAIL)
    git add --all
    git commit -m "[skip ci] build from azure"
    git push -f origin master
  displayName: 'Deploy to GitHub Pages'