baseurl = "https://www.meganii.com/"
title = "SIS Lab"
theme = "tailwindcss"
contentDir = "content"
publishDir = "public"

hasCJKLanguage = true
summaryLength = 100
DefaultContentLanguage = "ja"

enableGitInfo = true
Paginate = 12

[permalinks]
blog = "/blog/:year/:month/:day/:slug/"

[Languages]
[Languages.ja]
LanguageCode = 'ja'
lang = ""
title = "SIS Lab"
profile = "ギークを夢見るじょーぶん男子。「広く浅くから広く深く」を目指してブログを書いています。"
description = "メーカー系SIerブログ。趣味のプログラミング、旅行。日々、学んだことについて書きます。"
[Languages.en]
LanguageCode = 'en'
lang = "en/"
title = "SIS Lab"
profile = "I'm Software Engineer in Tokyo."
description = "I write about programming, traveling and studying."
weight = 2

[params]
themeColor = "gray"
Author = "meganii"
Birth = "Sun, March 3, 1988"
DateForm = "Mon, Jan 2, 2006"
adsensePublisher = "ca-pub-5340212676785058"
adsenseAd001 = "7368951150"
googleAnalytics = "UA-38171597-1"
GoogleAnalyticsUserID = "UA-38171597-1"
Twitter = "meganii"
Github = "https://github.com/meganii"
Facebook = "meganiicom"
FacebookAppId = "385471528156440"
Instagram = "meganii"
Cloudinary = "meganii"
ShowTagCloud = true
ShowRelatedPost = true
Disqus = "meganii"
SyntaxHighlightTheme = "solarized_dark.min.css"
logo = "/images/meganii_logo.png"
AnalyticsURL = "https://us-central1-cloud-api-2e3ec.cloudfunctions.net/function-1"
dateformat = "Jan 2, 2006" # Optional
latestSize = 5 # Optional
ampscripts = """
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
<script async custom-element="amp-auto-ads" src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js"></script>
"""
profile = "ギークを夢見るじょーぶん男子。「広く浅くから広く深く」を目指してブログを書いています。"
[params.topBanner]
src = "v1524390254/sislab_top_banner.png"
width = "1000"
height = "250"

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 50
# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true
# Will lower case keywords in both queries and in the indexes.
toLower = true
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 300
toLower = true
[[related.indices]]
name  = "category"
weight = 100
toLower = true
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"


[taxonomies]
tag = "tags"
category = "category"

[author]
name = "meganii"
homepage = "https://www.meganii.com/"


[menu]
  [[menu.categories]]
  identifier = "tech"
  name = "This is the tech section"
  title = "Tech"
  url = "category/tech/"
  weight = 10
  [[menu.categories]]
  identifier = "life"
  name = "This is the life section"
  title = "Life"
  url = "category/life/"
  weight = 20
  [[menu.categories]]
  identifier = "travel"
  name = "This is the travel section"
  title = "Travel"
  url = "category/travel/"
  weight = 30
  [[menu.categories]]
  identifier = "activity"
  name = "This is the travel section"
  title = "Activity"
  url = "category/activity/"
  weight = 30
  [[menu.categories]]
  identifier = "stationery"
  name = "This is the stationery section"
  title = "Stationery"
  url = "category/stationery/"
  weight = 40
  [[menu.categories]]
  identifier = "book"
  name = "This is the book section"
  title = "Book"
  url = "category/book/"
  weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4